#pragma once

#define USBMIDI_NAMESPACE usbMidi
#define BEGIN_USBMIDI_NAMESPACE \
    namespace USBMIDI_NAMESPACE \
    {
#define END_USBMIDI_NAMESPACE }

#define USING_NAMESPACE_USBMIDI using namespace USBMIDI_NAMESPACE;

BEGIN_USBMIDI_NAMESPACE

END_USBMIDI_NAMESPACE
